Controllers films users
AlexMAK1/java-filmorate pull request #1
Opened 2022-06-09 23:00 UTC by AlexMAK1

version 1.1

2022-06-10 23:08 UTC, makholin commented on .github/workflows/api-tests.yml
> -name: Films API Tests
этот файл не должен быть удален, он запускает тесты, которые проверяют правильность апи

2022-06-10 23:09 UTC, makholin commented on README.md
> -Template repository for Filmorate project.
этот файл тоже не стоит удалять
лучше добавить сюда описание проекта

2022-06-10 23:10 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
нужно отформатировать отступы

2022-06-10 23:10 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
можно заменить аннотацией `@Sl4j`

2022-06-10 23:11 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int i = 0;
стоит сделать отдельный генератор ид и использовать его, как сервис
создавать его можно используя аннотацию спринга @Service и Dependency Injection

2022-06-10 23:12 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        LocalDate realize = LocalDate.of(1895, 12, 28);
стоит вынести в константу `EARLIEST_RELEASE_DATE`

2022-06-10 23:13 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.debug("Валидация не пройдена: {}", film);
по такому сообщению будет не понятно, почему валидация не прошла
лучше для каждого кейса сделать отдельный if, и бросать исключения с разными сообщениями на каждый случай

2022-06-10 23:15 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final HashMap<Integer,User> users = new HashMap<>();
тип должен быть Map

нужно отформатировать код ctrl alt L

2022-06-10 23:16 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isEmpty() || len > 200 || film.getReleaseDate().isBefore(realize) || film.getDuration() < 0) {
валидацию стоит вынести в отдельный метод, который либо ничего не возвращает, либо выбрасывает исключение

2022-06-10 23:17 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/ValidationException.java
> +public class ValidationException extends Exception {
можно наследовать от RuntimeException, тогда не придется указывать это исключение в сигнатурах методов

2022-06-10 23:19 UTC, makholin requested changes
Нужно исправить замечания

Изменения нужно делать в этой же ветке, при пуше новые коммиты автоматически добавятся в этот пулл реквест

2022-06-11 11:31 UTC, AlexMAK1 commented on .github/workflows/api-tests.yml
> -name: Films API Tests
done

2022-06-11 11:32 UTC, AlexMAK1 commented on README.md
> -Template repository for Filmorate project.
done

2022-06-11 11:32 UTC, AlexMAK1 commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
done

2022-06-11 11:32 UTC, AlexMAK1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
done

2022-06-11 16:24 UTC, AlexMAK1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        LocalDate realize = LocalDate.of(1895, 12, 28);
done

2022-06-11 16:24 UTC, AlexMAK1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final HashMap<Integer,User> users = new HashMap<>();
done

2022-06-11 16:33 UTC, AlexMAK1 commented on src/main/java/ru/yandex/practicum/filmorate/model/ValidationException.java
> +public class ValidationException extends Exception {
done

2022-06-11 17:47 UTC, AlexMAK1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.debug("Валидация не пройдена: {}", film);
done

2022-06-11 17:47 UTC, AlexMAK1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isEmpty() || len > 200 || film.getReleaseDate().isBefore(realize) || film.getDuration() < 0) {
done

2022-06-12 09:57 UTC, makholin commented on pom.xml
> +			<artifactId>spring-context</artifactId>
странно, что тебе понадобилась отдельно эта зависимость
при добавлении спринга, его контекст сразу доступен

2022-06-12 09:57 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
пустые строки перед телом метода не нужны

2022-06-12 09:58 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@Slf4j
аннотации лучше располагать в порядке увеличения их длины, так проще читать код

2022-06-12 09:58 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.debug("Название фильма не может быть пустым: {}", film.getName());
при критических ошибках стоит делать уровень логирования **error**

2022-06-12 09:59 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException();
в само исключение тоже стоит добавить какое-то сообщение об ошибке

2022-06-12 10:00 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/IdGeneratorFilm.java
> +public class IdGeneratorFilm {
лучше назвать `FilmIdGenerator`

2022-06-12 10:01 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/IdGeneratorUser.java
> +        id = id+1;
нужно добавить пробелы

2022-06-12 10:01 UTC, makholin requested changes
Нужно исправить замечания

2022-06-12 13:45 UTC, AlexMAK1 commented on pom.xml
> +			<artifactId>spring-context</artifactId>
done

2022-06-12 13:46 UTC, AlexMAK1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
done

2022-06-12 13:48 UTC, AlexMAK1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@Slf4j
done

2022-06-12 13:51 UTC, AlexMAK1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.debug("Название фильма не может быть пустым: {}", film.getName());
done

2022-06-12 13:57 UTC, AlexMAK1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException();
done

2022-06-12 13:58 UTC, AlexMAK1 commented on src/main/java/ru/yandex/practicum/filmorate/service/IdGeneratorFilm.java
> +public class IdGeneratorFilm {
done

2022-06-12 13:59 UTC, AlexMAK1 commented on src/main/java/ru/yandex/practicum/filmorate/service/IdGeneratorUser.java
> +        id = id+1;
done

2022-06-12 14:13 UTC, AlexMAK1 commented
Исправил замечания.

2022-06-13 21:45 UTC, makholin approved these changes
Работа принята

2022-06-13 22:49 UTC, merged