Add friends likes
AlexMAK1/java-filmorate pull request #3
Opened 2022-06-22 00:27 UTC by AlexMAK1

2022-06-23 08:43 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            @RequestParam(defaultValue = "10") Long count
10 можно вынести в константу

2022-06-23 08:46 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getInMemoryFilmStorage().getFilms().values();
у сервисов не должно быть геттеров для внутренних полей
вместо предоставления доступа к полям в сервисе нужно сделать публичные методы, внутри которых осуществляется доступ к полям

```
public Film getById(int id) {
   return storage.getFilmById(id);
}
```

2022-06-23 09:02 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likes = new HashSet<>();
правильно, что коллекция сразу инициализирована
стоит сделать final, чтобы сама коллекция не менялась, а менялись только значения в ней

2022-06-23 09:02 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmIdGenerator.java
> +        return id = id +1L;
нужно добавить  пробел после +

2022-06-23 09:05 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        log.info("Добавляем в список друзей");
стоит добавить в лог кто кого добавил в друзья
`log.info("Добавление в друзья. Юзер 1: {}, Юзер 2: {}", id, friendId);`

2022-06-23 09:07 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        log.info("Находим друзей пользователя: {}", friends);
по логу будет не понятно, чьи друзья найдены

2022-06-23 09:09 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return films;
лучше возвращать копию мапы, чтобы в других классах по ссылке на мапу нельзя было получить доступ к этому полю

2022-06-23 09:09 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public InMemoryFilmStorage(FilmIdGenerator filmIdGenerator) {
конструктор должен быть первым в списке методов у класса

2022-06-23 09:11 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private void validation(Film film) {
для валидации лучше сделать отдельный класс ValidationService, который будет добавляться в этот класс как спринг компонент

2022-06-23 09:12 UTC, makholin requested changes
Нужно исправить замечания

2022-06-23 23:07 UTC, AlexMAK1 commented
внес изменения.

2022-06-25 08:41 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final String countValue = "10";
константа должна выглядеть так 
`private static final String DEFAULT_FILMS_AMOUNT = "10"`

2022-06-25 08:46 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        Map<Long, Film> newFilms = films;
так копия мапы не создается, а в newFilms лежит ссылка на поле этого класса, и она же передается во внешние классы, которые смогут менять содержимое по ссылке
чтобы создать  новый объект коллекции со нужными элементами, можно сделать так:

`return new HashMap<>(films)`

так будет возвращаться каждый раз новый объект

2022-06-25 08:47 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        Map<Long, User> newUsers = users;
тут тоже нужно исправить возвращение коллекции

2022-06-25 08:48 UTC, makholin requested changes
Нужно исправить замечания

2022-06-25 14:45 UTC, AlexMAK1 commented
исправил замечания

2022-06-26 13:01 UTC, makholin approved these changes
Работа принята

2022-07-09 16:04 UTC, merged