Add database
AlexMAK1/java-filmorate pull request #7
Opened 2022-07-16 02:43 UTC by AlexMAK1

versiom 1.2

2022-07-16 02:44 UTC, AlexMAK1 commented
version 1.2

2022-07-16 08:49 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        log.info(String.valueOf(e));
лучше сделать уровень логирования error
и выводить не все исключение, а его тип и сообщение 
`log.error("Выброшено исключение: {}: {}", e.getClass(), e.getMessage());`

2022-07-16 08:51 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@RestController
если есть эта аннотация, то аннотация Component уже не нужна

2022-07-16 08:51 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +import java.util.Collection;
нужно разделить импорты и аннотации пустой строкой

2022-07-16 08:54 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +
достаточно одной пустой строки

2022-07-16 08:55 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +@Getter
эти аннотации можно заменить на @Data

2022-07-16 08:56 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getCountPopularFilms(Integer count) {
правильнее будет `getPopularFilmsCount`

2022-07-16 08:59 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>              log.error("Ошибка, такого пользователя нет: {}", id);
для такого условия лог выглядит не очень подходящим, потому что судя по условии в бд вообще нет юзеров

2022-07-16 09:00 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private static MpaDbStorage mpaDbStorage;
должен быть не static 
нужно добавить final

2022-07-16 09:01 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            // TODO not found
нужно доделать

2022-07-16 09:03 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    static Film makeFilm(ResultSet rs, int rowNum) throws SQLException {
статические методы не принято использовать в классах-бинах спринга 
нужно сделать обычным приватным методом

приватные методы должны находиться после публичных

2022-07-16 09:04 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDBStorage.java
> +            // TODO not found
нужно доделать

2022-07-16 09:07 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDBStorage.java
> +        } catch (Throwable e) {
когда перехватывается Throwable, там может быть абсолютно любое исключение, даже OutOfMemoryError или StackOverflowException

логически неправильно перехватывая любое исключение потом выбрасывать ValidationException

во первых нужно перехватывать только те исключения, которые надо обработать
например, NotFoundException тут не надо обрабатывать, он может быть проброшен до самого ExceptionHandler и там преобразован в http код

2022-07-16 09:08 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/MpaDbStorage.java
> +    private static Mpa makeMpa(ResultSet rs, int rowNum) throws SQLException {
тоже нужно сделать не статичным методом

2022-07-16 09:12 UTC, makholin requested changes
нужно исправить замечания

2022-07-16 14:19 UTC, AlexMAK1 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>              log.error("Ошибка, такого пользователя нет: {}", id);
удалил данный метод, он вообще не используется и дублируется с методом` public User getUser(long id)`

2022-07-16 15:26 UTC, AlexMAK1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDBStorage.java
> +        } catch (Throwable e) {
Убрал конструкцию try catch, т.к. есть ErrorHadler и он сейчас настроен правильно. Спасибо!

2022-07-16 15:36 UTC, AlexMAK1 commented
внес изменения

2022-07-17 09:39 UTC, makholin approved these changes
Работа принята

2022-07-17 11:54 UTC, merged